"""
02_build_dashboard_data.py
Aggregates the cleaned dataset into the small data file the dashboard reads.

Outputs TWO copies of the same aggregates:
  - dashboard/dashboard_data.js   -> `window.__NOSHOW_DATA__ = {...}`  (loaded by the HTML;
                                     works both on GitHub Pages AND when opened as a local file)
  - dashboard/dashboard_data.json -> portable copy for reuse / inspection

This is the step that makes the dashboard live: change the data, re-run the pipeline,
and every graph updates from these files.

Run:  python3 scripts/02_build_dashboard_data.py
"""
from pathlib import Path
import json
import pandas as pd

BASE = Path(__file__).resolve().parents[1]
SRC = BASE / "data" / "processed" / "appointments_clean.csv"
OUT = BASE / "dashboard"

df = pd.read_csv(SRC, parse_dates=["ScheduledDay", "AppointmentDay"])

def grp(col, order=None):
    g = df.groupby(col, observed=True)["no_show"].agg(["mean", "count"])
    if order:
        g = g.reindex(order)
    return [{"label": str(i), "rate": round(100 * r["mean"], 1), "count": int(r["count"])}
            for i, r in g.iterrows()]

agg = {}
agg["kpi"] = {
    "total": int(len(df)),
    "no_shows": int(df["no_show"].sum()),
    "rate": round(100 * df["no_show"].mean(), 1),
    "patients": int(df["PatientId"].nunique()),
}
agg["by_tier"] = grp("risk_tier", ["Low", "Medium", "High"])
agg["by_lead"] = grp("lead_bucket", ["same-day", "1-3d", "4-7d", "8-14d", "15-30d", "30d+"])
agg["by_age"] = grp("age_bucket", ["0-17", "18-34", "35-54", "55-74", "75+"])
agg["by_weekday"] = grp("appt_weekday",
                        ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"])

sms = df.groupby("sms_received").agg(rate=("no_show", "mean"),
                                     lead=("lead_days", "mean"), n=("no_show", "count"))
agg["sms"] = [{"label": "No SMS" if i == 0 else "SMS sent",
               "rate": round(100 * r["rate"], 1),
               "avg_lead": round(r["lead"], 1), "count": int(r["n"])}
              for i, r in sms.iterrows()]

eq = df.groupby("Scholarship")["no_show"].mean()
agg["equity"] = {"welfare": round(100 * eq.get(1, 0), 1),
                 "non_welfare": round(100 * eq.get(0, 0), 1)}

h = df[df["prior_appts"] > 0].copy()
h["coh"] = pd.cut(h["prior_no_show_rate"], [-0.01, 0.0001, 0.5, 1.01],
                  labels=["Never missed", "Sometimes missed", "Frequently missed"])
agg["history"] = [{"label": str(i), "rate": round(100 * r["mean"], 1), "count": int(r["count"])}
                  for i, r in h.groupby("coh", observed=True)["no_show"].agg(["mean", "count"]).iterrows()]

c = df.groupby("Neighbourhood")["no_show"].agg(["mean", "count"])
c = c[c["count"] >= 1000].sort_values("mean", ascending=False).head(8)
agg["top_clinics"] = [{"label": str(i), "rate": round(100 * r["mean"], 1), "count": int(r["count"])}
                      for i, r in c.iterrows()]

wk = df.copy()
wk["week"] = wk["AppointmentDay"].dt.tz_localize(None).dt.to_period("W").dt.start_time
tr = wk.groupby("week")["no_show"].agg(["mean", "count"])
tr = tr[tr["count"] >= 200]
agg["trend"] = [{"week": i.strftime("%Y-%m-%d"), "rate": round(100 * r["mean"], 1), "count": int(r["count"])}
                for i, r in tr.iterrows()]
agg["date_range"] = [df["AppointmentDay"].min().strftime("%Y-%m-%d"),
                     df["AppointmentDay"].max().strftime("%Y-%m-%d")]
agg["generated_at"] = pd.Timestamp.utcnow().strftime("%Y-%m-%d %H:%M UTC")

# JSON (portable) + JS (loadable via <script>, no CORS/file:// issues)
(OUT / "dashboard_data.json").write_text(json.dumps(agg, indent=2))
(OUT / "dashboard_data.js").write_text(
    "// AUTO-GENERATED by scripts/02_build_dashboard_data.py — do not edit by hand.\n"
    "window.__NOSHOW_DATA__ = " + json.dumps(agg, indent=2) + ";\n"
)
print(f"Wrote dashboard_data.js and dashboard_data.json  "
      f"(no-show rate {agg['kpi']['rate']}%, {agg['kpi']['total']:,} appts, generated {agg['generated_at']})")
