"""
02_build_dashboard_data.py
Aggregates the cleaned dataset into the small data file the dashboard reads.

Outputs TWO copies of the same aggregates:
  - dashboard/dashboard_data.js   -> `window.__NOSHOW_DATA__ = {...}`  (loaded by the HTML;
                                     works both on GitHub Pages AND when opened as a local file)
  - dashboard/dashboard_data.json -> portable copy for reuse / inspection

This is the step that makes the dashboard live: change the data, re-run the pipeline,
and every graph updates from these files.

Run:  python3 scripts/02_build_dashboard_data.py
"""
from pathlib import Path
import json
import numpy as np
import pandas as pd

BASE = Path(__file__).resolve().parents[1]
SRC = BASE / "data" / "processed" / "appointments_clean.csv"
OUT = BASE / "dashboard"

df = pd.read_csv(SRC, parse_dates=["ScheduledDay", "AppointmentDay"])

def grp(col, order=None):
    g = df.groupby(col, observed=True)["no_show"].agg(["mean", "count"])
    if order:
        g = g.reindex(order)
    return [{"label": str(i), "rate": round(100 * r["mean"], 1), "count": int(r["count"])}
            for i, r in g.iterrows()]

agg = {}
agg["kpi"] = {
    "total": int(len(df)),
    "no_shows": int(df["no_show"].sum()),
    "rate": round(100 * df["no_show"].mean(), 1),
    "patients": int(df["PatientId"].nunique()),
}
agg["by_tier"] = grp("risk_tier", ["Low", "Medium", "High"])
agg["by_lead"] = grp("lead_bucket", ["same-day", "1-3d", "4-7d", "8-14d", "15-30d", "30d+"])
agg["by_age"] = grp("age_bucket", ["0-17", "18-34", "35-54", "55-74", "75+"])
agg["by_weekday"] = grp("appt_weekday",
                        ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"])

sms = df.groupby("sms_received").agg(rate=("no_show", "mean"),
                                     lead=("lead_days", "mean"), n=("no_show", "count"))
agg["sms"] = [{"label": "No SMS" if i == 0 else "SMS sent",
               "rate": round(100 * r["rate"], 1),
               "avg_lead": round(r["lead"], 1), "count": int(r["n"])}
              for i, r in sms.iterrows()]

eq = df.groupby("Scholarship")["no_show"].mean()
agg["equity"] = {"welfare": round(100 * eq.get(1, 0), 1),
                 "non_welfare": round(100 * eq.get(0, 0), 1)}

h = df[df["prior_appts"] > 0].copy()
h["coh"] = pd.cut(h["prior_no_show_rate"], [-0.01, 0.0001, 0.5, 1.01],
                  labels=["Never missed", "Sometimes missed", "Frequently missed"])
agg["history"] = [{"label": str(i), "rate": round(100 * r["mean"], 1), "count": int(r["count"])}
                  for i, r in h.groupby("coh", observed=True)["no_show"].agg(["mean", "count"]).iterrows()]

c = df.groupby("Neighbourhood")["no_show"].agg(["mean", "count"])
c = c[c["count"] >= 1000].sort_values("mean", ascending=False).head(8)
agg["top_clinics"] = [{"label": str(i), "rate": round(100 * r["mean"], 1), "count": int(r["count"])}
                      for i, r in c.iterrows()]

wk = df.copy()
wk["week"] = wk["AppointmentDay"].dt.tz_localize(None).dt.to_period("W").dt.start_time
tr = wk.groupby("week")["no_show"].agg(["mean", "count"])
tr = tr[tr["count"] >= 200]
agg["trend"] = [{"week": i.strftime("%Y-%m-%d"), "rate": round(100 * r["mean"], 1), "count": int(r["count"])}
                for i, r in tr.iterrows()]
agg["date_range"] = [df["AppointmentDay"].min().strftime("%Y-%m-%d"),
                     df["AppointmentDay"].max().strftime("%Y-%m-%d")]
agg["generated_at"] = pd.Timestamp.utcnow().strftime("%Y-%m-%d %H:%M UTC")

# JSON (portable) + JS (loadable via <script>, no CORS/file:// issues)
(OUT / "dashboard_data.json").write_text(json.dumps(agg, indent=2))
(OUT / "dashboard_data.js").write_text(
    "// AUTO-GENERATED by scripts/02_build_dashboard_data.py — do not edit by hand.\n"
    "window.__NOSHOW_DATA__ = " + json.dumps(agg, indent=2) + ";\n"
)

# ---------------------------------------------------------------------------
# Compact row-level data → powers the dashboard's INTERACTIVE FILTERS.
# Every categorical field is encoded as an integer index into a small
# dictionary, so ~110k rows compress to a few MB. The dashboard recomputes
# all charts client-side whenever the viewer changes a filter.
# ---------------------------------------------------------------------------
tiers = ["Low", "Medium", "High"]
leads = ["same-day", "1-3d", "4-7d", "8-14d", "15-30d", "30d+"]
ages = ["0-17", "18-34", "35-54", "55-74", "75+"]
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
hist_cats = ["First visit", "Never missed", "Sometimes missed", "Frequently missed"]
clinics = sorted(df["Neighbourhood"].astype(str).unique())
clinic_idx = {c: i for i, c in enumerate(clinics)}

wk = df["AppointmentDay"].dt.tz_localize(None).dt.to_period("W").dt.start_time
week_list = sorted(wk.unique())
week_idx = {w: i for i, w in enumerate(week_list)}
week_labels = [pd.Timestamp(w).strftime("%Y-%m-%d") for w in week_list]

hist_code = np.where(df["prior_appts"] == 0, 0,
            np.where(df["prior_no_show_rate"] == 0, 1,
            np.where(df["prior_no_show_rate"] < 0.5, 2, 3)))

rows = list(map(list, zip(
    df["risk_tier"].map({t: i for i, t in enumerate(tiers)}).astype(int),
    df["lead_bucket"].map({t: i for i, t in enumerate(leads)}).astype(int),
    df["age_bucket"].map({t: i for i, t in enumerate(ages)}).astype(int),
    df["appt_weekday"].map({t: i for i, t in enumerate(weekdays)}).astype(int),
    df["Neighbourhood"].astype(str).map(clinic_idx).astype(int),
    df["sms_received"].astype(int),
    df["Scholarship"].astype(int),
    pd.Series(hist_code).astype(int),
    wk.map(week_idx).astype(int),
    df["no_show"].astype(int),
    df["lead_days"].clip(lower=0).astype(int),
)))

rowsdata = {
    "meta": {"date_range": agg["date_range"], "generated_at": agg["generated_at"], "total": int(len(df))},
    "cols": ["tier", "lead", "age", "weekday", "clinic", "sms", "sch", "hist", "week", "noshow", "leadDays"],
    "fields": {"tier": tiers, "lead": leads, "age": ages, "weekday": weekdays,
               "clinic": clinics, "hist": hist_cats, "week": week_labels},
    "rows": rows,
}
(OUT / "dashboard_rows.js").write_text(
    "// AUTO-GENERATED by scripts/02_build_dashboard_data.py — do not edit by hand.\n"
    "window.__NOSHOW_ROWS__ = " + json.dumps(rowsdata, separators=(",", ":")) + ";\n"
)

rows_kb = (OUT / "dashboard_rows.js").stat().st_size / 1024
print(f"Wrote dashboard_data.js, dashboard_data.json, dashboard_rows.js "
      f"({len(rows):,} rows, {rows_kb:.0f} KB)  "
      f"— no-show rate {agg['kpi']['rate']}%, generated {agg['generated_at']}")
